DROP TABLE IF EXISTS ROBOT cascade;
DROP TABLE IF EXISTS CUSTOMER cascade;

-- ROBOT
CREATE TABLE ROBOT (
    id_robot SERIAL NOT NULL,
    id_customer INTEGER,
    price INTEGER NOT NULL,
    model VARCHAR(256) NOT NULL,
    purchase_date DATE NOT NULL
);
ALTER TABLE ROBOT ADD CONSTRAINT pk_robot PRIMARY KEY (id_robot);

-- CUSTOMER
CREATE TABLE CUSTOMER (
    id_customer SERIAL NOT NULL,
    name VARCHAR(40) NOT NULL
);
ALTER TABLE CUSTOMER ADD CONSTRAINT pk_customer PRIMARY KEY (id_customer);

ALTER TABLE ROBOT ADD CONSTRAINT fk_robot_customer FOREIGN KEY (id_customer)
    REFERENCES CUSTOMER (id_customer) ON DELETE CASCADE;